### ISSUE TITLE
Exception during timing of request

### ISSUE THREAD

**Issue by Chive** [opbeat/opbeat_python#53] opened 2015-07-24 19:53 UTC
**Python 2.7.3 / Django 1.4.21 / opbeat 3.0.2**

I cannot say for sure since when we've been experiencing these errors as they did not appear on our exception tracking, but they sure spam the gunicorn log (notice the timestamps).

```bash
INFO 2015-07-24 21:39:40,728 connectionpool 25145 140665733502720 Starting new HTTPS connection (1): example.com
ERROR 2015-07-24 21:39:40,863 __init__ 25145 140665733502720 Exception during timing of request
Traceback (most recent call last):
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/contrib/django/middleware/__init__.py", line 174, in process_response
    self.client.end_transaction(status_code, view_func)
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/base.py", line 584, in end_transaction
    self.instrumentation_store.transaction_end(status_code, name)
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/traces.py", line 232, in transaction_end
    transaction.end_transaction()
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/traces.py", line 27, in end_transaction
    return self.end_trace(skip_frames)
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/traces.py", line 45, in end_trace
    trace = self.trace_stack.pop()
IndexError: pop from empty list

ERROR 2015-07-24 21:39:41,250 __init__ 25141 140665733502720 Exception during timing of request
Traceback (most recent call last):
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/contrib/django/middleware/__init__.py", line 174, in process_response
    self.client.end_transaction(status_code, view_func)
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/base.py", line 584, in end_transaction
    self.instrumentation_store.transaction_end(status_code, name)
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/traces.py", line 232, in transaction_end
    transaction.end_transaction()
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/traces.py", line 27, in end_transaction
    return self.end_trace(skip_frames)
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/traces.py", line 45, in end_trace
    trace = self.trace_stack.pop()
IndexError: pop from empty list

ERROR 2015-07-24 21:39:41,292 __init__ 25144 140665733502720 Exception during timing of request
Traceback (most recent call last):
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/contrib/django/middleware/__init__.py", line 174, in process_response
    self.client.end_transaction(status_code, view_func)
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/base.py", line 584, in end_transaction
    self.instrumentation_store.transaction_end(status_code, name)
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/traces.py", line 232, in transaction_end
    transaction.end_transaction()
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/traces.py", line 27, in end_transaction
    return self.end_trace(skip_frames)
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/traces.py", line 45, in end_trace
    trace = self.trace_stack.pop()
IndexError: pop from empty list

INFO 2015-07-24 21:39:42,585 connectionpool 25143 140665447913216 Starting new HTTPS connection (1): another-example.org
ERROR 2015-07-24 21:39:42,842 __init__ 25143 140665733502720 Exception during timing of request
Traceback (most recent call last):
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/contrib/django/middleware/__init__.py", line 174, in process_response
    self.client.end_transaction(status_code, view_func)
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/base.py", line 584, in end_transaction
    self.instrumentation_store.transaction_end(status_code, name)
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/traces.py", line 232, in transaction_end
    transaction.end_transaction()
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/traces.py", line 27, in end_transaction
    return self.end_trace(skip_frames)
  File "/home/user/app/local/lib/python2.7/site-packages/opbeat/traces.py", line 45, in end_trace
    trace = self.trace_stack.pop()
IndexError: pop from empty list
```
If you need any more info, I'll be happy to provide it :)

**Comment by piquadrat** [comment] 2015-07-24 20:19
Thanks for the report! We'll try to reproduce.

**Comment by piquadrat** [comment] 2015-08-03 08:42
@Chive this should be fixed in 3.0.4. Can you verify? If you're still seeing it, feel free to reopen this issue!

**Closed by piquadrat** 2015-08-03 08:42 UTC

**Comment by rossgray** [comment] 2016-12-14 15:09
Hi,

I am reopening this issue because I have noticed the same problem in our application. Let me know if you prefer that I open a separate issue for it. We are running **Python 3.5.2 / Flask 0.11.1 / Opbeat 3.5.1**

We get the following from various points in our code when under medium load:

```
trace = self.trace_stack.pop()
IndexError: pop from empty list
```

An example:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1644, in full_dispatch_request
request_finished.send(self, response=response)
File "/usr/local/lib/python3.5/site-packages/blinker/base.py", line 267, in send
for receiver in self.receivers_for(sender)]
File "/usr/local/lib/python3.5/site-packages/blinker/base.py", line 267, in <listcomp>
for receiver in self.receivers_for(sender)]
File "/usr/local/lib/python3.5/site-packages/opbeat/contrib/flask/__init__.py", line 207, in request_finished
self.client.end_transaction(rule, response.status_code)
File "/usr/local/lib/python3.5/site-packages/opbeat/base.py", line 589, in end_transaction
self.instrumentation_store.transaction_end(status_code, name)
File "/usr/local/lib/python3.5/site-packages/opbeat/traces.py", line 254, in transaction_end
transaction.end_transaction()
File "/usr/local/lib/python3.5/site-packages/opbeat/traces.py", line 50, in end_transaction
return self.end_trace(skip_frames)
File "/usr/local/lib/python3.5/site-packages/opbeat/traces.py", line 68, in end_trace
trace = self.trace_stack.pop()
IndexError: pop from empty list
```

Could some exception handling be added to the Opbeat client to prevent issues like this breaking our application?

If you need any more information please let me know.

Thanks

**Comment by rossgray** [comment] 2016-12-14 16:56
Sorry ignore the above comment - I have created a separate issue for this: #144
